server:
  port: 8010
spring:
  application:
    name: microservice-consumer-movie
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:pwd123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true

microservice-provider-user:           # 使用配置文件的方式修改该微服务的Ribbon客户端的负载均衡规则   <clientName>.ribbon.XXX
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
